name: Create and push file
on:
  schedule:
    - cron:  '0 4 * * *' # Runs at 9:30 AM IST (4:00 UTC)

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:  
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create file
      run: date > hello_world2.txt

    - name: Commit and push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Add hello_world.txt"
        git push
