name: Ngrok Workflow
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Specify the desired Python version

    - name: Set up Apache and PHP
      run: |
        sudo apt-get -y install apache2
        sudo apt-get -y update && sudo apt-get -y upgrade && sudo apt -y update && sudo apt -y upgrade
        sudo add-apt-repository -y ppa:ondrej/php
        sudo apt-get -y update && sudo apt-get -y upgrade && sudo apt -y update && sudo apt -y upgrade && sudo apt -y install unzip
        sudo apt install -y php7.4
        sudo apt install -y php7.4-common php7.4-mysql php7.4-xml php7.4-xmlrpc php7.4-curl php7.4-gd php7.4-imagick php7.4-cli php7.4-dev php7.4-imap php7.4-mbstring php7.4-opcache php7.4-soap php7.4-zip php7.4-intl
        sudo service apache2 restart
        php -r 'echo "\n\nYour PHP installation is working fine.\n\n\n";'
        
    - name: Clone Repository and Configure
      run: |
        cd /var/www
        sudo rm -r html
        sudo git clone https://github.com/PBhadoo/Rapidleech html
        cd /var/www/html
        sudo mkdir files
        sudo chmod 777 files
        sudo chmod 777 configs
        sudo chmod 777 configs/files.lst
        sudo rm -rf rar
        sudo wget https://rarlab.com/rar/rarlinux-x64-612.tar.gz
        sudo tar -xvf rarlinux-x64-612.tar.gz
        sudo rm -f rarlinux-x64-612.tar.gz
        sudo chmod -R 777 rar
        sudo chmod -R 777 rar/*
        
    - name: Set up ngrok
      run: |
        wget -O ngrok.tgz https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
        tar -xvf ngrok.tgz
        ./ngrok authtoken 2LgAs7npvh1Vu7X6TDvaDEfAhMR_45V9PxjYgiT34nz6A8UjM
        ./ngrok http 80 &
        sleep 10
        
    - name: Get ngrok Tunnel URL
      run: |
        curl http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url'

      run: python -m http.server 5000

