name: Ngrok Workflow
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Specify the desired Python version

    - name: Install dependencies
      run: |
        pip install pyngrok
        
    - name: Install Apache2
      run: |
        sudo apt-get update && sudo apt-get install -y apache2
        sudo service apache2 start

    - name: Download ngrok
      run: |
        wget -O ngrok.tgz https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
        tar -xvf ngrok.tgz
        ./ngrok authtoken 2LgAs7npvh1Vu7X6TDvaDEfAhMR_45V9PxjYgiT34nz6A8UjM
        ./ngrok http 80 &
        sleep 10  # Adjust this time if needed
        curl http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url'

    # - name: Run Python script
    #   run: |
    #     python - <<EOF
    #     from pyngrok import ngrok

    #     # start the server
    #     public_url = ngrok.connect(addr="80")
    #     print(f"Public URL: {public_url}")
    #     EOF

    - name: Start local server
      run: python -m http.server 5000

