name: Rapid Leech Workflow

on: [push]

jobs:
  run_rapid_leech:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install ngrok
      run: |
        wget -O ngrok.tgz https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
        tar -xvf ngrok.tgz
        ./ngrok config add-authtoken 1x1iUeEkvs2FdBw3tDB4cpQ09h3_51iNFXXyoobXvmx7PiB8V

    - name: Start Apache2
      run: |
        sudo service apache2 start

    - name: Run ngrok in background
      run: |
        ./ngrok http 80 > ngrok_output.log &

    - name: Wait for ngrok to start
      run: |
        sleep 10 # Wait for ngrok to initialize
        while true; do
          ngrok_url=$(grep -o "http://.*" ngrok_output.log)
          if [ -n "$ngrok_url" ]; then
            echo "ngrok tunnel is ready: $ngrok_url"
            break
          fi
          sleep 2
        done
