name: Ngrok Workflow
on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Specify the desired Python version

    - name: Install dependencies
      run: |
        pip install pyngrok

    - name: Download ngrok
      run: |
        wget -O ngrok.tgz https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
        tar -xvf ngrok.tgz
        ./ngrok authtoken 1x1iUeEkvs2FdBw3tDB4cpQ09h3_51iNFXXyoobXvmx7PiB8V

    - name: Run Python script
      run: |
        python - <<EOF
        from pyngrok import ngrok

        # start the server
        public_url = ngrok.connect(addr="5000")
        print(f"Public URL: {public_url}")
        EOF

    - name: Start local server
      run: python -m http.server 5000

